export const generateRandomPlayers = (quantity: number) => {
  const names = [
    "Liam",
    "Emma",
    "Noah",
    "Olivia",
    "William",
    "Ava",
    "James",
    "Isabella",
    "Oliver",
    "Sophia",
    "Benjamin",
    "Charlotte",
    "Elijah",
    "Mia",
    "Lucas",
    "Amelia",
    "Mason",
    "Harper",
    "Logan",
    "Evelyn",
    "Alexander",
    "Abigail",
    "Henry",
    "Emily",
    "Jackson",
    "Elizabeth",
    "Sebastian",
    "Sofia",
    "Aiden",
    "Avery",
    "Matthew",
    "Ella",
    "Samuel",
    "Scarlett",
    "David",
    "Grace",
    "Joseph",
    "Chloe",
    "Carter",
    "Victoria",
    "Owen",
    "Riley",
    "Wyatt",
    "Aria",
    "John",
    "Lily",
    "Jack",
    "Aubrey",
    "Luke",
    "Zoey",
    "Jayden",
    "Penelope",
    "Dylan",
    "Lillian",
    "Grayson",
    "Addison",
    "Levi",
    "Stella",
    "Isaac",
    "Natalie",
    "Gabriel",
    "Hannah",
    "Julian",
    "Willow",
    "Mateo",
    "Layla",
    "Anthony",
    "Eleanor",
    "Jaxon",
    "Hazel",
    "Lincoln",
    "Violet",
    "Joshua",
    "Aurora",
    "Christopher",
    "Nora",
  ];

  const lastNames = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Miller",
    "Davis",
    "Garcia",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Rivera",
    "Campbell",
    "Mitchell",
    "Carter",
    "Roberts",
    "Gomez",
    "Phillips",
    "Evans",
    "Turner",
    "Diaz",
    "Parker",
    "Cruz",
    "Edwards",
    "Collins",
    "Reyes",
    "Stewart",
    "Morris",
    "Morales",
    "Murphy",
    "Cook",
    "Rogers",
    "Morgan",
    "Peterson",
    "Cooper",
    "Reed",
    "Bailey",
    "Bell",
    "Gomez",
    "Kelly",
    "Howard",
    "Ward",
    "Cox",
    "Diaz",
    "Richardson",
    "Wood",
  ];

  const randomNames = [];

  for (let i = 0; i < quantity; i++) {
    const randomFirstNameIndex = Math.floor(Math.random() * names.length);
    const randomLastNameIndex = Math.floor(Math.random() * lastNames.length);
    const randomFirstName = names[randomFirstNameIndex];
    const randomLastName = lastNames[randomLastNameIndex];
    const fullName = `${randomFirstName} ${randomLastName}`;
    const found = randomNames.some((item) => item.name === fullName);

    if (!found) {
      randomNames.push({
        name: fullName,
        award: 420000.0,
        vote: "",
      });
    } else {
      i--;
    }
  }

  return randomNames;
};
